<?php
   $translate = $this->plugin('translate');

// This is all commented out because we know that there are no item sets or site pages involved.
// $searchType = $this->siteSetting('search_type', 'sitewide');
// switch ($searchType) {
//     case 'cross-site':
//         $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
//         break;
//     case 'sitewide':
//     default:
//         //$searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);

         $searchAction = $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], true);
// }

$searchValue = $this->escapeHtml($this->params()->fromQuery('property[0][text]', ''));
?>

<!-- Here we build a query predominantly of hard-coded values in hidden form fields. -->
<!-- for more info, see the Omeka developer API Docs                                 --> 
<form action="<?php echo $this->escapeHtml($searchAction); ?>" id="search-form">
    <input type="text" name="property[0][text]" value="<?php echo $searchValue; ?>" 
        placeholder="<?php echo $translate('Place Name Contains'); ?>"
        aria-label="<?php echo $translate('Place Name Contains'); ?>">
     
     <!-- Make sure that the Sort_By field is listed  in th Item Browse --> 
     <input type="hidden"  name="sort_by" data-name="sort_by" value="cdash:streetSort">
     <input type="hidden"  name="sort_order" data-name="sort_order" value="asc">
     <input type="hidden"  name='resource_template_id[]' value='13'>

     <input type="hidden"  name='property[0][joiner]' value='and' >
     <input type="hidden"  name='property[0][property]' value='1' >
     <input type="hidden"  name='property[0][type]' value='in'>
     


     <?php /*
     <input type="hidden"  name='property[1][joiner]' value='or' >
     <input type="hidden"  name='property[1][property]' value='538' >
     <input type="hidden"  name='property[1][type]' value='in'>
     <input type="hidden"  name='property[1][text]' value="<?php echo $searchValue; ?>" >
     */ ?>

     <script type="text/javascript">
         function searchURL(){
            window.location = "http://www.myurl.com/search/" + (input text value);
            var dataValue = search-form.getAttribute("data-value");
        }
       </script>

     <button class="fa fa-camera-retro" type="submit"><?php echo $translate('CDASHSearch'); ?></button>
</form>