<?php $infodot = $this->assetUrl('img/infodot.png'); ?>
  
  <p><b>Base Maps</b></p>
  <input type="radio" name="mapchoice" id="camBase"  >
  <label for="camBase">Cambridge Basemap</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDDBasemap/MapServer/">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="bluesky2023"  >
  <label for="bluesky2023">Cambridge 2023 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam2021"  >
  <label for="cam21">Cambridge 2021 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam2018"  >
  <label for="camPhoto">Cambridge 2018 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam2010"  >
  <label for="cam2010">Cambridge 2010 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam1995"  >
  <label for="cam1995">Cambridge 1995 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam1978"  >
  <label for="cam1978">Cambridge 1978 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam1969"  >
  <label for="cam1969">Cambridge 1969 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>
  <input type="radio" name="mapchoice" id="cam1947"  >
  <label for="cam1947">Cambridge 1947 Photo</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span></div>
  <br>

  <input type="radio" name="mapchoice" id="cam1930"  >
  <label for="cam1930">1930 Bromley </label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://mapwarper.net/layers/546">MapWarper.org</a></a></span></div>
  <br>

  <input type="radio" name="mapchoice" id="bromley1916"  >
  <label for="bromley1916">1916 Bromley</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="">Cambridge GIS</a></span></div>
  <br>

  <input type="radio" id="bromley1894" name="mapchoice">
  <label for="bromley1894">1894 Bromley</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://mapjunction.com/VIEWER/17810" target="Cdash_Link">MapJunction</a>, <a href="https://mapwarper.net/layers/920" target="Cdash_Link">MapWarper</a></span></div>

<br>
  <input type="radio" id="hopkins1873" name="mapchoice">
  <label for="hopkins1873">1873 Hopkins</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://collections.leventhalmap.org/search/commonwealth:tt44pw432" target="Cdash_Link">Leventhal Map and Education Center </a> at Boston Public Library</span></div>
  <br>
  <input type="radio" id="chase1865" name="mapchoice">
  <label for="chase1865">1865 J.G. Chase</label>
  <div class="tooltip"><img src=<?php echo $infodot; ?>> 
  <span class="tooltiptext">Shared by <a href="https://gis.cambridgema.gov/arcgis/rest/services/CDASH/MapServer">Cambridge GIS</a></span>
  </div>



<!-- /div -->  <!-- Closes basemaps column -->